### PR TITLE
Add BDFL governance model

### LINKED ISSUE #65: Choose a Governance Model
After research doing in #29 we need to choose a proper Governance model for Boken project.

### PR DESCRIPTION
**Pull request by s3rrot**
The aim here is to **discuss about the proper governance model** we want to implement on Boken project, and thus create and refine the final governance.md. Here are provided two different boilerplates:

* **Benevolent Dictatorship** Model
* **Liberal** Model

First of all we need to chose one of them. After that we can work on refinement of different aspects of selected option.

Main **points to be defined/discussed are highlighted with TBD prefix** (e.g. the ones related with communication through mailing list, which we don't have yet).

Feel free to make suggestions about. Thanks.

This should close #65

### CODE REVIEW

**Comment by cgbosse** [comment]
From my side, given that we are currently at the beginning of the project to avoid additional complexity I vote for the Benevolent Dictatorship model.
At later stages when we have a larger community of lets say 50 contributors or so we can reconsider the governance model.

**Comment by s3rrot** [comment]
> From my side, given that we are currently at the beginning of the project to avoid additional complexity I vote for the Benevolent Dictatorship model.
> At later stages when we have a larger community of lets say 50 contributors or so we can reconsider the governance model.

I agree with @cgbosse about starting with the BD model and as soon as the project evolves we can move toward more openly democratic systems. What do you think @yeraydavidrodriguez @josecelano?

**Comment by yeraydavidrodriguez** [comment]
As it seems reasonable to think that the project will remain in semi-obscurity for some time, I think it is adequate to remain in a more agile governance model until all objectives of this stage are met: a full-fledged demo, attractive pack of features, a webpage, some publicity and community work... so I agree also with the BD model for the moment.

**Review by yeraydavidrodriguez — APPROVED** [review]
Ready to be merged. Nice job S3RROT

**Pull request merged**
