### PR TITLE
Add document on research Governance Models

### LINKED ISSUE #29: Legal & governance: Define a governance model
We need to decide how we want to rule the interactions on the project. In order to do so, we will research about different types of governance models and the possibilities they offer.

### PR DESCRIPTION
**Pull request by s3rrot**
First version on Research Governance Models document

Close #29

### CODE REVIEW

**Comment by s3rrot** [comment]
TO-DO list (I'm working on it):

- [ ] Include additional examples of Open Source Projects (e.g. NodeJS)
- [ ] Define main actions to discuss which model of governance we want to adopt.
- [ ] Create GOVERNANCE.md document

**Review by cgbosse — APPROVED** [review]
I think that it is a clear overall explanation of the possibilities of a possible governance models for our project. Thank you for the good work.

**Comment by s3rrot** [comment]
> TO-DO list (I'm working on it):
> 
> * [x]  Include additional examples of Open Source Projects (e.g. NodeJS)
> * [x]  Define main actions to discuss which model of governance we want to adopt.
> * [ ]  ~~Create GOVERNANCE.md document~~ To be done in #65 

Although my first idea was to include the conversation to define and choose our Governance model here, I have created an additional issue (#65) to do that there instead. So this one is ready to be reviewed.

**Review by yeraydavidrodriguez — DISMISSED** [review]
Nice job s3rrot.

**Review by yeraydavidrodriguez — DISMISSED** [review]

**Review by yeraydavidrodriguez — APPROVED** [review]

**Pull request merged**
